---
default: &default
  adapter: postgres
  user: <%= ENV['DB_USER'] %>
  password: "<%= ENV['DB_PASS'] %>"
  host: <%= ENV['DB_HOST'] %>
  database: <%= ENV['DB_NAME'] %>

development:
  <<: *default

production:
  <<: *default

test:
  <<: *default
