---
apt_packages:
  - make
  - g++
  - libpq-dev
  - mc
  - vim
  - ruby2.5-dev

ruby_version: 2.5

postgresql_databases:
  - name: projects_db
    owner: admin_123

postgresql_users:
  - name: admin_123
    pass: 123456
postgresql_user_privileges:
  - name: admin_123
    db: projects_db
    priv: "ALL"
    role_attr_flags: "SUPERUSER"
